apiVersion: v1
kind: pod
metadata:
  name: invalid-kind-value
  labels:
    owner: frodo-baggins
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP