apiVersion: v1
kind: Pod
metadata:
  name: invalid-lable-value
  labels:
    owner: ---
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP