apiVersion: v1
kind: Pod
metadata:
  name: invalid-protocol-type
  labels:
    owner: frodo-baggins
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: 22