apiVersion: v1
kind: Pod
metadata:
  name: invalid-spec-key
  labels:
    owner: frodo-baggins
Spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP