apiVersion: v1
kind: Pod
metadata:
  name: missing-image
  labels:
    owner: frodo-baggins
spec:
  containers:
    - name: web
      ports:
        - name: web
          containerPort: 80
          protocol: TCP