apiVersion: v1
kind: Pod
metadata:
  name: wrong-k8s-indentation
  labels:
    owner: frodo-baggins
spec:
containers:
  - name: web
    image: nginx
    ports:
      - name: web
        containerPort: 80
        protocol: TCP